"""
Django settings for esimCloud project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY", 'kk5tq+=kyyicitl+1ki!wyx@*mz^vmei6_q25dt!^3(_kxd^eg')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.environ.get("DJANGO_DEBUG", default=True) == 'True')

ALLOWED_HOSTS = ['0.0.0.0', 'localhost', '127.0.0.1']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',
    'django_filters',
    'corsheaders',
    'drf_yasg',
    'rest_framework',
    'rest_framework.authtoken',
    'social_django',
    'inline_actions',
    'djoser',
    'simulationAPI',
    'authAPI',
    'libAPI',
    'saveAPI',
    'publishAPI',
    'arduinoAPI',
    'workflowAPI',
    'ltiAPI',
    'chatbotAPI',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    # Task 4: Inject trace_id / session_id correlation IDs into every request
    'simulationAPI.middleware.CorrelationIdMiddleware',
    # Task 3: Per-user API rate limiting + concurrent-job limit
    'simulationAPI.middleware.SimulationRateLimitMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'esimCloud.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'esimCloud.wsgi.application'

AUTH_USER_MODEL = 'authAPI.User'
# Database config Defaults to sqlite3 if not provided in environment files

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("SQL_DATABASE",
                               os.path.join(BASE_DIR, "db.sqlite3")),
        "USER": os.environ.get("SQL_USER", "user"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "5432"),
    },
}

DATABASE_ROUTERS = (
    # 'simulationAPI.dbrouters.mongoRouter',<- to Store models in mongodb
    # 'saveAPI.dbrouters.mongoRouter',<- to Store saveAPI models in mongodb
    # 'libAPI.dbrouters.mongoRouter'<- to Store LibAPI models in mongodb
)

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  # noqa
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  # noqa
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',  # noqa
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',  # noqa
    },
]

# Mail server config

# use this for console emails
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Note SMTP is slow
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
# EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "email@gmail.com")
# EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "gmailpassword")
# EMAIL_PORT = os.environ.get("EMAIL_PORT", 587)
# EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", True)

SOCIAL_AUTH_GOOGLE_OAUTH2_KEY = os.environ.get(
    "SOCIAL_AUTH_GOOGLE_OAUTH2_KEY", "")

SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = os.environ.get(
    "SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET", "")

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")

GOOGLE_OAUTH_REDIRECT_URI = os.environ.get(
    "GOOGLE_OAUTH_REDIRECT_URI", "http://localhost/api/auth/google-callback")

POST_ACTIVATE_REDIRECT_URL = os.environ.get(
    "POST_ACTIVATE_REDIRECT_URL", "http://localhost/")

# AI Assistant API Key
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")

DJOSER = {
    'SEND_ACTIVATION_EMAIL': True,
    'PASSWORD_RESET_CONFIRM_URL': 'eda/#/password/reset/confirm/{uid}/{token}',
    'PASSWORD_RESET_CONFIRM_RETYPE': True,
    'SET_PASSWORD_RETYPE': True,
    # 'USERNAME_RESET_CONFIRM_URL': '#/username/reset/confirm/{uid}/{token}',
    'ACTIVATION_URL': 'api/auth/users/activate/{uid}/{token}',
    'SOCIAL_AUTH_ALLOWED_REDIRECT_URIS': [
      "http://localhost:8000/api/auth/google-callback",
      "http://localhost/api/auth/google-callback", GOOGLE_OAUTH_REDIRECT_URI],  # noqa
    'SOCIAL_AUTH_TOKEN_STRATEGY': 'authAPI.token.TokenStrategy',
    'PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND': True,
    'SERIALIZERS': {
        'token_create': 'authAPI.serializers.TokenCreateSerializer',
    },
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
}

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'social_core.backends.google.GoogleOAuth2',
)

# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Allow CORS for Public API
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost',
    'http://127.0.0.1:3000',
    'http://127.0.0.1'
]

# Static files for django admin and DRF
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_URL = '/django_static/'

# File Storage
FILE_STORAGE_ROOT = os.path.join(BASE_DIR, 'file_storage')
FILE_STORAGE_URL = '/files'

# noqa For Netlist handling netlist uploads and other temp uploads
MEDIA_URL = '/files/'
MEDIA_ROOT = os.path.join(BASE_DIR, "file_storage")

# celery
CELERY_BROKER_URL = os.environ.get('CELERY_BROKER_URL', 'redis://redis:6379')
CELERY_RESULT_BACKEND = os.environ.get('CELERY_RESULT_BACKEND', 'redis://redis:6379')
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_IMPORTS = (
    'simulationAPI.tasks',
    'arduinoAPI.tasks'
)

# Task 1: Celery Beat – periodic stale-job recovery (every 60 s)
# Task 6: Celery Beat – data hygiene tasks (daily)
from celery.schedules import crontab  # noqa: E402
CELERY_BEAT_SCHEDULE = {
    'recover-stale-simulation-jobs': {
        'task': 'simulationAPI.tasks.recover_stale_jobs',
        'schedule': 60.0,   # every 60 seconds
    },
    'cleanup-old-simulation-jobs': {
        'task': 'simulationAPI.maintenance_tasks.cleanup_old_simulation_jobs',
        'schedule': crontab(hour=2, minute=0),  # daily at 02:00
    },
    'cleanup-orphan-files': {
        'task': 'simulationAPI.maintenance_tasks.cleanup_orphan_files',
        'schedule': crontab(hour=3, minute=0),  # daily at 03:00
    },
}

# Task 6: Data retention periods (days)
SIM_JOB_RETENTION_DAYS = int(os.environ.get('SIM_JOB_RETENTION_DAYS', 30))
SIM_ARTIFACT_RETENTION_DAYS = int(os.environ.get('SIM_ARTIFACT_RETENTION_DAYS', 7))

# Task 3: Rate limiting + concurrency settings
SIM_RATE_LIMIT_REQUESTS = int(os.environ.get('SIM_RATE_LIMIT_REQUESTS', 20))
SIM_RATE_LIMIT_WINDOW = int(os.environ.get('SIM_RATE_LIMIT_WINDOW', 60))    # seconds
SIM_MAX_CONCURRENT_JOBS = int(os.environ.get('SIM_MAX_CONCURRENT_JOBS', 3))
SIM_RATE_LIMIT_PATHS = ['/api/simulation/']

# Task 2: Simulation timeout defaults (seconds, 0 = no limit)
SIM_QUEUE_WAIT_TIMEOUT = int(os.environ.get('SIM_QUEUE_WAIT_TIMEOUT', 300))
SIM_POD_PROVISION_TIMEOUT = int(os.environ.get('SIM_POD_PROVISION_TIMEOUT', 120))
SIM_EXECUTION_TIMEOUT = int(os.environ.get('SIM_EXECUTION_TIMEOUT', 300))

# Task 4: Structured JSON logging with correlation-ID support
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'json': {
            '()': 'simulationAPI.middleware.StructuredJsonFormatter',
        },
        'simple': {
            'format': '[%(asctime)s] %(levelname)s %(name)s: %(message)s',
        },
    },
    'handlers': {
        'console_json': {
            'class': 'logging.StreamHandler',
            'formatter': 'json',
        },
        'console_simple': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console_json'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console_json'],
            'level': 'WARNING',
            'propagate': False,
        },
        'simulationAPI': {
            'handlers': ['console_json'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'celery': {
            'handlers': ['console_json'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Bearer': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header'
        }
    }
}

LTI_TOOL_CONFIGURATION = {
    'title': 'Esim-Cloud',
    'description': 'Esim cloud is a simulation platform',
    'launch_url': 'api/lti/auth/',
    'course_aware': True,
    'course_navigation': True
}


SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
